# Generated by Django 5.2.6 on 2025-09-20 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("logger_name", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("pathname", models.CharField(blank=True, max_length=500)),
                ("funcName", models.CharField(blank=True, max_length=100)),
                ("lineno", models.IntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("request_path", models.CharField(blank=True, max_length=500)),
                ("request_method", models.CharField(blank=True, max_length=10)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("extra_data", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "system_logs",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(fields=["level"], name="system_logs_level_245244_idx"),
                    models.Index(
                        fields=["created"], name="system_logs_created_2c0cc2_idx"
                    ),
                    models.Index(
                        fields=["logger_name"], name="system_logs_logger__b2fa76_idx"
                    ),
                    models.Index(
                        fields=["user"], name="system_logs_user_id_85bc8b_idx"
                    ),
                ],
            },
        ),
    ]
