# Generated by Django 5.2.6 on 2025-09-19 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_platforms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialAccountAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscriber_count", models.BigIntegerField(blank=True, null=True)),
                ("video_count", models.IntegerField(blank=True, null=True)),
                ("view_count", models.BigIntegerField(blank=True, null=True)),
                ("follower_count", models.BigIntegerField(blank=True, null=True)),
                ("following_count", models.BigIntegerField(blank=True, null=True)),
                ("media_count", models.IntegerField(blank=True, null=True)),
                ("connection_count", models.IntegerField(blank=True, null=True)),
                ("tweet_count", models.IntegerField(blank=True, null=True)),
                ("likes_count", models.BigIntegerField(blank=True, null=True)),
                (
                    "engagement_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("last_post_date", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="social_platforms.usersocialaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Account Analytics",
                "verbose_name_plural": "Social Account Analytics",
                "db_table": "social_account_analytics",
            },
        ),
    ]
