# Generated by Django 5.2.6 on 2025-09-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_platforms", "0002_socialaccountanalytics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersocialaccount",
            name="profile_picture_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
