# Generated by Django 5.2.6 on 2025-09-25 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_platforms", "0003_alter_usersocialaccount_profile_picture_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialaccountanalytics",
            name="average_engagement",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="socialaccountanalytics",
            name="linkedin_follower_count",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialaccountanalytics",
            name="linkedin_managed_pages",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialaccountanalytics",
            name="linkedin_post_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialaccountanalytics",
            name="linkedin_profile_views",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialaccountanalytics",
            name="linkedin_search_appearances",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialaccountanalytics",
            name="linkedin_total_organizations",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialaccountanalytics",
            name="recent_posts_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialaccountanalytics",
            name="recent_total_comments",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialaccountanalytics",
            name="recent_total_likes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialaccountanalytics",
            name="recent_total_shares",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialaccountanalytics",
            name="recent_total_views",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="LinkedInOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("vanity_name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                ("industry", models.CharField(blank=True, max_length=255)),
                ("company_size", models.CharField(blank=True, max_length=100)),
                ("logo_url", models.URLField(blank=True)),
                ("cover_photo_url", models.URLField(blank=True)),
                ("follower_count", models.BigIntegerField(blank=True, null=True)),
                ("employee_count_range", models.CharField(blank=True, max_length=100)),
                ("user_role", models.CharField(blank=True, max_length=100)),
                ("is_admin", models.BooleanField(default=False)),
                ("can_post", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linkedin_organizations",
                        to="social_platforms.usersocialaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "LinkedIn Organization",
                "verbose_name_plural": "LinkedIn Organizations",
                "db_table": "linkedin_organizations",
                "unique_together": {("account", "organization_id")},
            },
        ),
        migrations.CreateModel(
            name="LinkedInPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.CharField(max_length=255, unique=True)),
                ("urn", models.CharField(blank=True, max_length=500)),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("ARTICLE", "Article"),
                            ("RICH_MEDIA", "Rich Media"),
                            ("UGC_POST", "User Generated Content"),
                            ("VIDEO", "Video"),
                            ("IMAGE", "Image"),
                            ("TEXT", "Text Only"),
                        ],
                        default="UGC_POST",
                        max_length=20,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PUBLISHED", "Published"),
                            ("DRAFT", "Draft"),
                            ("PROCESSING", "Processing"),
                            ("READY", "Ready"),
                        ],
                        default="PUBLISHED",
                        max_length=20,
                    ),
                ),
                ("text_content", models.TextField(blank=True)),
                (
                    "media_urls",
                    models.JSONField(default=list, help_text="List of media URLs"),
                ),
                ("article_url", models.URLField(blank=True)),
                ("article_title", models.CharField(blank=True, max_length=500)),
                ("article_description", models.TextField(blank=True)),
                ("like_count", models.IntegerField(default=0)),
                ("comment_count", models.IntegerField(default=0)),
                ("share_count", models.IntegerField(default=0)),
                ("view_count", models.IntegerField(default=0)),
                ("click_count", models.IntegerField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("last_modified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linkedin_posts",
                        to="social_platforms.usersocialaccount",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="social_platforms.linkedinorganization",
                    ),
                ),
            ],
            options={
                "verbose_name": "LinkedIn Post",
                "verbose_name_plural": "LinkedIn Posts",
                "db_table": "linkedin_posts",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["account", "published_at"],
                        name="linkedin_po_account_8041fd_idx",
                    ),
                    models.Index(
                        fields=["organization", "published_at"],
                        name="linkedin_po_organiz_3d5037_idx",
                    ),
                    models.Index(fields=["state"], name="linkedin_po_state_b8b4c1_idx"),
                ],
            },
        ),
    ]
