# Generated by Django 5.2.6 on 2025-10-10 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "social_platforms",
            "0005_instagramanalytics_linkedinanalytics_tiktokanalytics_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="InstagramMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_id", models.CharField(max_length=255, unique=True)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("IMAGE", "Image"),
                            ("VIDEO", "Video"),
                            ("CAROUSEL_ALBUM", "Carousel Album"),
                        ],
                        default="IMAGE",
                        max_length=20,
                    ),
                ),
                ("media_url", models.URLField(blank=True)),
                ("permalink", models.URLField(blank=True)),
                ("caption", models.TextField(blank=True)),
                ("like_count", models.IntegerField(default=0)),
                ("comments_count", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instagram_media",
                        to="social_platforms.usersocialaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instagram Media",
                "verbose_name_plural": "Instagram Media",
                "db_table": "instagram_media",
                "ordering": ["-timestamp", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["account", "timestamp"],
                        name="instagram_m_account_20886e_idx",
                    ),
                    models.Index(
                        fields=["media_type"], name="instagram_m_media_t_376821_idx"
                    ),
                ],
            },
        ),
    ]
