# Generated by Django 5.2.6 on 2025-10-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_platforms", "0006_instagrammedia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instagramanalytics",
            options={
                "verbose_name": "Instagram Business Analytics",
                "verbose_name_plural": "Instagram Business Analytics",
            },
        ),
        migrations.AlterModelOptions(
            name="instagrammedia",
            options={
                "ordering": ["-timestamp", "-created_at"],
                "verbose_name": "Instagram Business Media",
                "verbose_name_plural": "Instagram Business Media",
            },
        ),
        migrations.AddField(
            model_name="instagramanalytics",
            name="average_impressions_per_post",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="instagramanalytics",
            name="average_reach_per_post",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="instagramanalytics",
            name="facebook_page_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="instagramanalytics",
            name="facebook_page_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="instagramanalytics",
            name="profile_views",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="instagramanalytics",
            name="recent_total_saves",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="instagramanalytics",
            name="recent_total_shares",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="instagramanalytics",
            name="website_clicks",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="instagrammedia",
            name="engagement_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="instagrammedia",
            name="impressions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="instagrammedia",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="instagrammedia",
            name="reach",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="instagrammedia",
            name="saved",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="instagrammedia",
            name="scheduled_publish_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instagrammedia",
            name="video_views",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="instagramanalytics",
            name="account_type",
            field=models.CharField(default="BUSINESS", max_length=20),
        ),
        migrations.AlterField(
            model_name="instagramanalytics",
            name="is_business_account",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="instagrammedia",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("IMAGE", "Image"),
                    ("VIDEO", "Video"),
                    ("CAROUSEL_ALBUM", "Carousel Album"),
                    ("STORY", "Story"),
                ],
                default="IMAGE",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="instagrammedia",
            index=models.Index(
                fields=["is_published"], name="instagram_m_is_publ_f67bda_idx"
            ),
        ),
    ]
